USE [master]
GO

/****** Object:  Database [CodeFormatter]    Script Date: 28/03/2017 15:18:58 ******/
CREATE DATABASE [CodeFormatter] ON  PRIMARY 
( NAME = N'CodeFormatter', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL.1\MSSQL\DATA\CodeFormatter.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'CodeFormatter_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL.1\MSSQL\DATA\CodeFormatter_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

--ALTER DATABASE [CodeFormatter] SET COMPATIBILITY_LEVEL = 90
--GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CodeFormatter].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CodeFormatter] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CodeFormatter] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CodeFormatter] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CodeFormatter] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CodeFormatter] SET ARITHABORT OFF 
GO

ALTER DATABASE [CodeFormatter] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CodeFormatter] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CodeFormatter] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CodeFormatter] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CodeFormatter] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CodeFormatter] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CodeFormatter] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CodeFormatter] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CodeFormatter] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CodeFormatter] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CodeFormatter] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CodeFormatter] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CodeFormatter] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CodeFormatter] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CodeFormatter] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CodeFormatter] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CodeFormatter] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CodeFormatter] SET  MULTI_USER 
GO

ALTER DATABASE [CodeFormatter] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CodeFormatter] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CodeFormatter] SET  READ_WRITE 
GO


